config/routes.rb
PodcastNetwork::Application.routes.draw do

  devise_for :admins

  match 'episodes/:id/edit', :to => 'episodes#edit',  :as => 'episode_edit'
  match ':podcast_shortname/:episode_number/edit', :to => 'episodes#edit',  :as => 'episode_edit'
  match ':podcast_shortname/edit',                 :to => 'podcasts#edit',  :as => 'podcast_edit'

  resources :podcasts, :episodes

  match ':podcast_shortname',                      :to => 'podcasts#show',  :as => 'podcast_show'
  match ':podcast_shortname.rss',                  :to => 'podcasts#show',  :as => 'podcast_rss',  :format => 'rss'
  match ':podcast_shortname/rss',                  :to => 'podcasts#show',  :as => 'podcast_rss2', :format => 'rss'
  match ':podcast_shortname/feed',                 :to => 'podcasts#show',  :as => 'podcast_feed', :format => 'rss'
  match ':podcast_shortname/:episode_number',      :to => 'episodes#show',  :as => 'episode_show'

  root :to => 'podcasts#index'

end

app/models/episode.rb
class Episode < ActiveRecord::Base
  belongs_to :podcast
  attr_accessible :episode_number, :title, :summary, :author, :body, :media_url, :podcast_id, :publish_date,
  :media_length, :media_size, :media_title, :media_artist, :media_album, :media_year, :media_track

  # after_initialize :load_file_properties_from_database
  # after_save :load_file_properties_into_database

  def summary
    if @summary.nil?
      return @body
    else 
      return @summary
    end
  end

  def sort_order
    if episode_number[0,1] == 'p'
      return episode_number[1..-1].to_i - 100
    else
      return episode_number.to_i
    end
  end

  def local_url
    if media_url.nil? || media_url.length == 0 
      return nil
    end    
    'public/brickcaster.resources/' + media_url.split('http://resources.brickcaster.com/')[1]    
  end    

  def media_size
    if @media_size.nil?
      load_file_properties_into_database
      return 0
    end
    @media_size
  end

  def load_file_properties_from_database
    tags = attributes
    @media_length = tags['media_length']
    @media_size = tags['media_size']
    @media_title = tags['media_title']
    @media_artist = tags['media_artist']
    @media_album = tags['media_album']
    @media_year = tags['media_year']
    @media_track = tags['media_track']
    @summary = tags['summary']
  end

  def load_file_properties_into_database
    tags = load_file_properties
    if tags.nil?
      return nil
    end
    @media_length = tags['length']
    @media_size = tags['size']
    @media_title = tags['title']
    @media_artist = tags['artist']
    @media_album = tags['album']
    @media_year = tags['year']
    @media_track = tags['track']
    update_column(:media_length, @media_length)
    update_column(:media_size, @media_size)
    update_column(:media_title, @media_title)
    update_column(:media_artist, @media_artist)
    update_column(:media_album, @media_album)
    update_column(:media_year, @media_year)
    update_column(:media_track, @media_track)
  end

  def load_file_properties
    if ( not local_url ) || ( not File.exist? ( local_url ) )
      return nil
    end
    child = {}    
    child['size'] = File.size( local_url )   
    Mp3Info.open( local_url ) do |m|
      child['length'] = m.length       
      child['title'] = m.tag.title 
      child['artist'] = m.tag.artist
      child['album'] = m.tag.album 
      child['year'] = m.tag.year
      child['track'] = m.tag.track 
    end
    child
  end

end

app/controllers/episodes_controller.rb
class EpisodesController < ApplicationController

  before_filter :authenticate_admin!, :except => [:show, :index]

  # GET /episodes
  # GET /episodes.json
  def index
    @episodes = Episode.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @episodes }
    end
  end

  # GET /episodes/1
  # GET /episodes/1.json
  def show
    if params[:podcast_shortname]
      @podcast = Podcast.where(:shortname => params[:podcast_shortname]).first
      unless @podcast
        redirect_to root_path and return
      end
      @episode = Episode.where(:podcast_id => @podcast.id, :episode_number => params[:episode_number]).first
      unless @episode
        redirect_to podcast_show_path and return
      end
    else 
      redirect_to root_path and return      
    end

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @episode }
    end
  end

  # GET /episodes/new
  # GET /episodes/new.json
  def new
    @episode = Episode.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @episode }
    end
  end

  # GET /episodes/1/edit
  # GET /podcast_shortname/1/edit
  def edit
    if params[:podcast_shortname]
      @podcast = Podcast.where(:shortname => params[:podcast_shortname]).first
      @episode = Episode.where(:podcast_id => @podcast.id, :episode_number => params[:episode_number]).first
    elsif params[:id]
      @episode = Episode.find(params[:id])
      redirect_to episode_edit_path(@episode.podcast.shortname, @episode.episode_number)
    end
  end

  # POST /episodes
  # POST /episodes.json
  def create
    @episode = Episode.new(params[:episode])

    respond_to do |format|
      if @episode.save
        format.html { redirect_to @episode, notice: 'Episode was successfully created.' }
        format.json { render json: @episode, status: :created, location: @episode }
      else
        format.html { render action: "new" }
        format.json { render json: @episode.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /episodes/1
  # PUT /episodes/1.json
  def update
    @episode = Episode.find(params[:id])

    respond_to do |format|
      if @episode.update_attributes(params[:episode])
        format.html { redirect_to @episode, notice: 'Episode was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @episode.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /episodes/1
  # DELETE /episodes/1.json
  def destroy
    @episode = Episode.find(params[:id])
    @episode.destroy

    respond_to do |format|
      format.html { redirect_to episodes_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/episodes_helper.rb
module EpisodesHelper

  def markdown_init
    rndr = Redcarpet::Render::HTML.new(:link_attributes => Hash["target" => "_blank"])
    Redcarpet::Markdown.new(
      rndr,
      :hard_wrap => true,                
      :autolink => true,
      :space_after_headers => true
    )
  end

  def process_markdown(body)
    markdown = markdown_init
    raw markdown.render(body)
  end

  def body_truncate(body)
    truncate(body, :length => 255, :separator => "\n")
  end

  def body_encode(body)
    process_markdown(body)
  end

  def format_length(length)
    if length.nil?
      return "00:00:00"
    end
    length = Time.at(length.to_i).utc.strftime("%H:%M:%S")
  end

  def format_date(date)
    if date.nil?
      return 0
    end
    date.rfc822
  end

  def format_date_human(date)
    if date.nil?
      return 0
    end
    date.strftime("%Y.%m.%d")
  end

end

app/views/episodes/_form.html.erb
<%= form_for @episode do |f| %>
  <% if @episode.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@episode.errors.count, "error") %> prohibited this episode from being saved:</h2>

      <ul>
      <% @episode.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br />
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :episode_number %><br />
    <%= f.text_field :episode_number %>
  </div>
  <div class="field">
    <%= f.label :author %><br />
    <%= f.text_field :author %>
  </div>
  <div class="field">
    <%= f.label :publish_date %><br />
    <%= f.text_field :publish_date %>
  </div>
  <div class="field">
    <%= f.label :podcast_id %><br />
    <%= f.select :podcast_id, options_for_select( Podcast.all.map { |podcast| [podcast.title, podcast.id] } ) %>
  </div>  
  <div class="field">
    <%= f.label :summary %><br />
    <%= f.text_area :summary %>
  </div>
  <div class="field">
    <%= f.label :body %><br />
    <%= f.text_area :body %>
  </div>
  <fieldset id="media-fields">
    <legend>Media (file) Properties</legend>
    <div class="field">
      <%= f.label :media_url %><br />
      <%= f.text_field :media_url %>
    </div>
    <div class="field">
      <%= f.label :media_length, "Media Length in seconds" %><br />
      <%= f.text_field :media_length %>
    </div>
    <div class="field">
      <%= f.label :media_size, "Media Size in bytes" %><br />
      <%= f.text_field :media_size %>
    </div>
    <div class="field">
      <%= f.label :media_title %><br />
      <%= f.text_field :media_title %>
    </div>
    <div class="field">
      <%= f.label :media_artist %><br />
      <%= f.text_field :media_artist %>
    </div>
    <div class="field">
      <%= f.label :media_album, "Media Album (podcast title)" %><br />
      <%= f.text_field :media_album %>
    </div>
    <div class="field">
      <%= f.label :media_year %><br />
      <%= f.text_field :media_year %>
    </div>
    <div class="field">
      <%= f.label :media_track, "Media Track (episode number)" %><br />
      <%= f.text_field :media_track %>
    </div>
  </fieldset>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/episodes/edit.html.erb
<h1>Editing episode</h1>

<%= render 'form' %>

<%= link_to 'Show', episode_show_path %> |
<%= link_to 'Back', podcast_show_path %>

app/views/episodes/index.html.erb
<% @episodes.sort_by! { |e| [ e.podcast.id, e.sort_order ] } %>

<h1>All episodes</h1>

<table>
<% @episodes.each do |episode| %>
  <tr>
  	<td><%= episode.podcast.title %>  &nbsp; </td>
  	<td><%= link_to episode.title, episode_show_path(episode.podcast.shortname, episode.episode_number) %></td>
  </tr>
<% end %>
</table>

app/views/episodes/new.html.erb
<h1>New episode</h1>

<%= render 'form' %>

<%= link_to 'Back', episodes_path %>

app/views/episodes/show.html.erb
<%= content_for :html_title do %><%= @episode.podcast.title %>, <%= @episode.title %><% end %>
<%= content_for :body_class do %>application episode<% end %>
<%= content_for :back_link do %><%= link_to '« ' + @episode.podcast.title, podcast_show_path(@episode.podcast.shortname) %><% end %>
<div class="episode-wrapper">
  <h1 class="episode-title">
    <%= @episode.title %>
  </h1>
  <div class="episode-topbar">
    <audio controls="controls">
      <source src="<%= @episode.media_url %>" type="audio/mpeg">
      <source src="<%= @episode.media_url %>" type="audio/mp3">Your browser does not support HTML5 audio.
    </audio>
    <%= link_to '(download)', @episode.media_url %>
  </div>
  <div class="episode-body">
    <%= body_encode(@episode.body) %>
    <br />
    <%= @episode.media_title %><br />
    <%= @episode.media_artist %><br />
    <%= @episode.media_album %><br />
    <%= format_date_human(@episode.publish_date) %><br />

    Duration: <%= format_length(@episode.media_length) %><br />

  </div>

</div>

<%= content_for :footer_links do %>
  <%= link_to 'Subscribe in iTunes', @episode.podcast.subscribe_itunes_link %>
  <%= link_to 'Subscribe in RSS', podcast_rss_path(@episode.podcast.shortname) %>
  <%= process_markdown(@episode.podcast.links) %>
<% end %>