config/routes.rb
PodcastNetwork::Application.routes.draw do

  devise_for :admins

  match 'episodes/:id/edit', :to => 'episodes#edit',  :as => 'episode_edit'
  match ':podcast_shortname/:episode_number/edit', :to => 'episodes#edit',  :as => 'episode_edit'
  match ':podcast_shortname/edit',                 :to => 'podcasts#edit',  :as => 'podcast_edit'

  resources :podcasts, :episodes

  match ':podcast_shortname',                      :to => 'podcasts#show',  :as => 'podcast_show'
  match ':podcast_shortname.rss',                  :to => 'podcasts#show',  :as => 'podcast_rss',  :format => 'rss'
  match ':podcast_shortname/rss',                  :to => 'podcasts#show',  :as => 'podcast_rss2', :format => 'rss'
  match ':podcast_shortname/feed',                 :to => 'podcasts#show',  :as => 'podcast_feed', :format => 'rss'
  match ':podcast_shortname/:episode_number',      :to => 'episodes#show',  :as => 'episode_show'

  root :to => 'podcasts#index'

end

app/models/podcast.rb
class Podcast < ActiveRecord::Base
  has_many :episodes
  attr_accessible :shortname, :title, :author, :body, :art_url, :art_url_medium, :art_url_wide,
  :links, :subscribe_itunes_link, :subscribe_feedburner_link, :keywords, :categories

end

app/controllers/podcasts_controller.rb
class PodcastsController < ApplicationController

  before_filter :authenticate_admin!, :except => [:show, :index] 

  # GET /podcasts
  # GET /podcasts.json
  def index
    @podcasts = Podcast.all
    @podcasts.sort_by! { |p| p.shortname.length }

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @podcasts }
    end
  end

  # GET /podcasts/1
  # GET /podcasts/1.json
  # GET /podcast_shortname
  def show
    if params[:podcast_shortname]
      @podcast = Podcast.where(:shortname => params[:podcast_shortname]).first
    elsif params[:id]
      @podcast = Podcast.find(params[:id])
      redirect_to podcast_show_path(@podcast.shortname) and return
    else 
      redirect_to root_path and return
    end

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @podcast }
      format.rss  # show.builder
    end
  end

  # GET /podcasts/new
  # GET /podcasts/new.json
  def new
    @podcast = Podcast.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @podcast }
    end
  end

  # GET /podcasts/1/edit
  # GET /podcast_shortname/edit
  def edit
    if params[:podcast_shortname] 
      @podcast = Podcast.where(:shortname => params[:podcast_shortname]).first
    elsif params[:id]
      @podcast = Podcast.find(params[:id])
      redirect_to podcast_edit_path(@podcast.shortname)
    end
  end

  # POST /podcasts
  # POST /podcasts.json
  def create
    @podcast = Podcast.new(params[:podcast])

    respond_to do |format|
      if @podcast.save
        format.html { redirect_to @podcast, notice: 'Podcast was successfully created.' }
        format.json { render json: @podcast, status: :created, location: @podcast }
      else
        format.html { render action: "new" }
        format.json { render json: @podcast.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /podcasts/1
  # PUT /podcasts/1.json
  def update
    @podcast = Podcast.find(params[:id])

    respond_to do |format|
      if @podcast.update_attributes(params[:podcast])
        format.html { redirect_to @podcast, notice: 'Podcast was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @podcast.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /podcasts/1
  # DELETE /podcasts/1.json
  def destroy
    @podcast = Podcast.find(params[:id])
    @podcast.destroy

    respond_to do |format|
      format.html { redirect_to podcasts_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/podcasts_helper.rb
module PodcastsHelper
end

app/views/podcasts/_episodes.html.erb
<% 
@episodes = @podcast.episodes
%>
<% if @episodes %>
<%
    @episodes.sort_by! { |e| e.publish_date.to_i }
    @episodes.reverse!
    @episodes.each do |episode| %>
    <div class="episode"><%= link_to episode.title, episode_show_path(@podcast.shortname, episode.episode_number) %></div>
  <% end %>
<% end %>
<br />

app/views/podcasts/_form.html.erb
<%= form_for @podcast do |f| %>
  <% if @podcast.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@podcast.errors.count, "error") %> prohibited this podcast from being saved:</h2>

      <ul>
      <% @podcast.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :shortname %><br />
    <%= f.text_field :shortname %>
  </div>
  <div class="field">
    <%= f.label :title %><br />
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :author %><br />
    <%= f.text_field :author %>
  </div>
  <div class="field">
    <%= f.label :body %><br />
    <%= f.text_area :body %>
  </div>
  <div class="field">
    <%= f.label :keywords %><br />
    <%= f.text_field :keywords %>
  </div>
  <div class="field">
    <%= f.label :categories %><br />
    <%= f.text_area :categories %>
  </div>
  <div class="field">
    <%= f.label :subscribe_itunes_link %><br />
    <%= f.text_field :subscribe_itunes_link %>
  </div>
  <div class="field">
    <%= f.label :subscribe_feedburner_link %><br />
    <%= f.text_field :subscribe_feedburner_link %>
  </div>
  <div class="field">
    <%= f.label :links %><br />
    <%= f.text_area :links %>
  </div>
  <div class="field">
    <%= f.label :art_url %><br />
    <%= f.text_field :art_url %>
  </div>
  <div class="field">
    <%= f.label :art_url_medium %><br />
    <%= f.text_field :art_url_medium %>
  </div>
  <div class="field">
    <%= f.label :art_url_wide %><br />
    <%= f.text_field :art_url_wide %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/podcasts/edit.html.erb
<h1>Editing podcast</h1>

<%= render 'form' %>

<%= link_to 'Show', podcast_show_path %> |
<%= link_to 'Back', podcasts_path %>

app/views/podcasts/index.html.erb
<%= content_for :html_title do %>brickcaster: small podcasts from the human edge<% end %>
<%= content_for :body_class do %>application podcast<% end %>

<div class="podcast-index-wrapper">
<% @podcasts.each do |podcast| %>
<div class="podcast-teaser">
  <%= link_to image_tag(podcast.art_url_medium, :border=>0), podcast_show_path(podcast.shortname) %>
  <h2 class="podcast-title"><%= link_to podcast.title, podcast_show_path(podcast.shortname) %></h2>
  <div class="podcast-body"><%= podcast.body %></div>
</div>
<% end %>
</div>
<br /><br /><br />

app/views/podcasts/new.html.erb
<h1>New podcast</h1>

<%= render 'form' %>

<%= link_to 'Back', podcasts_path %>

app/views/podcasts/show.html.erb
<%= content_for :html_title do %><%= @podcast.title %><% end %>
<%= content_for :body_class do %>application podcast<% end %>
<%= content_for :back_link do %><%= link_to '« All Podcasts', podcasts_path(), :class => 'white' %><% end %>
<%= content_for :art do %><%= @podcast.art_url_wide %><% end %>

<div class="podcast-wrapper">

  <h1 class="podcast-title">
    <%= @podcast.title %>
  </h1>

  <div class="podcast-body">
    <%= @podcast.body %>
  </div>

  <div class="podcast-episodes">
    <%= render 'episodes' %>
  </div>

</div>

<%= content_for :footer_links do %>
  <%= link_to 'Subscribe in iTunes', @podcast.subscribe_itunes_link %>
  <%= link_to 'Subscribe in RSS', podcast_rss_path(@podcast.shortname) %>
  <%= process_markdown(@podcast.links) %>
<% end %>